# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"PipelineSession": "dag.ipynb",
         "rmdir": "dag.ipynb",
         "pickle_load": "dag.ipynb",
         "pickle_dump": "dag.ipynb",
         "recursive_dict": "dag.ipynb",
         "undefault_dict": "dag.ipynb",
         "recursive_assign": "dag.ipynb",
         "folder_to_dict": "dag.ipynb",
         "dict_to_folder": "dag.ipynb",
         "BaseDAG": "dag.ipynb",
         "model_to_dot": "dag.ipynb",
         "DAGEstimator": "dag.ipynb",
         "unpack_inputs": "node.ipynb",
         "unpack_transform_inputs": "node.ipynb",
         "input_task_factory": "node.ipynb",
         "fit_task_factory": "node.ipynb",
         "transform_task_factory": "node.ipynb",
         "BaseNode": "node.ipynb",
         "InputTransformer": "node.ipynb",
         "NodeTransformer": "node.ipynb",
         "ConcatenateNode": "node.ipynb"}

modules = ["dag.py",
           "node.py"]

doc_url = "https://{user}.github.io/skdag/"

git_url = "https://github.com/{user}/skdag/tree/{branch}/"

def custom_doc_links(name): return None
