# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"pickle_load": "dag.ipynb",
         "pickle_dump": "dag.ipynb",
         "recursive_dict": "dag.ipynb",
         "undefault_dict": "dag.ipynb",
         "recursive_assign": "dag.ipynb",
         "folder_to_dict": "dag.ipynb",
         "dict_to_folder": "dag.ipynb",
         "BaseDAG": "dag.ipynb",
         "model_to_dot": "dag.ipynb",
         "DAGEstimator": "dag.ipynb",
         "BaseNode": "node.ipynb",
         "BaseInputNode": "node.ipynb",
         "Input": "node.ipynb",
         "Target": "node.ipynb",
         "NodeEstimator": "node.ipynb",
         "ConcatenateNode": "node.ipynb",
         "remove_folder_or_file": "utils.ipynb",
         "get_pointer_names": "utils.ipynb",
         "global_delete_from_reference": "utils.ipynb",
         "global_set_from_reference": "utils.ipynb",
         "global_delete_from_object": "utils.ipynb",
         "global_set_from_object": "utils.ipynb",
         "SimpleCacher": "utils.ipynb",
         "EstimatorCacher": "utils.ipynb"}

modules = ["dag.py",
           "node.py",
           "utils.py"]

doc_url = "https://{user}.github.io/skdag/"

git_url = "https://github.com/{user}/skdag/tree/{branch}/"

def custom_doc_links(name): return None
