# AUTOGENERATED! DO NOT EDIT! File to edit: notebooks_dev/utils.ipynb (unless otherwise specified).

__all__ = ['remove_folder_or_file']

# Cell
def remove_folder_or_file(path):
    '''
    recursively remove dir and files in dir given by direcotry(path)
    '''
    path = Path(path)
    if path.exists():
        if path.is_dir():
            rmtree(path)
        else:
            path.unlink()
    else:
        pass

    return